version: '3.8'

services:
  excel-interviewer:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/interviews.db
      - DEBUG=true
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8000
    env_file:
      - .env
    volumes:
      # Mount database directory for persistence
      - ./data:/app/data
      # Mount source code for development (comment out for production)
      - ./server:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: PostgreSQL for production-like development
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: excel_interviews
      POSTGRES_USER: interview_user
      POSTGRES_PASSWORD: dev_password_change_in_production
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    profiles: ["postgres"]  # Only start with --profile postgres

volumes:
  postgres_data:
